#!/bin/bash

OPTINDEX=1

# Initialize our own variables:
port=""
origin=""
name=""
user=""
identity=""
numhost=$(wc -l < ./ec2-hosts.txt)

while getopts "p:o:n:u:i:" opt; do
  case "$opt" in
    p)  port=$OPTARG
      ;;
    o)  origin=$OPTARG
      ;;
    n)  name=$OPTARG
      ;;
    u)	user=$OPTARG
      ;;
    i)  identity=$OPTARG
      ;;
  esac
done

shift $((OPTIND-1))

echo "Starting deploy procedure against arguments"
echo "port=$port, origin=$origin, name=$name, user=$user, identity=$identity"
echo ""

i=0
host=($(cut -d$'\t' -f1 ./ec2-hosts.txt))

for h in "${host[@]}"; do
  echo "Attempting deploy of replica againt ${h}"
  response=$(
  ssh -t -oStrictHostKeyChecking=no -i $identity $user@$h << ENDSSH &> /dev/null
  echo "hostname"
  if [ -d /home/$user/CDN ]
  then
    cd /home/$user/CDN
  else
    git clone https://github.com/pietdaniel/CDN.git
    cd /home/$user/CDN
  fi
  git reset --hard
  git checkout turn-in
  git pull origin turn-in
ENDSSH
)
done

echo "Attempting deploy of dns server againt cs5700cdnproject.ccs.neu.edu"

response=$(
  ssh -t -oStrictHostKeyChecking=no -i $identity $user@cs5700cdnproject.ccs.neu.edu << ENDSSH &> /dev/null
  if [ -d /home/$user/CDN ]
  then
    cd /home/$user/CDN
  else
    git clone https://github.com/pietdaniel/CDN.git
    cd /home/$user/CDN
  fi
  git reset --hard
  git checkout turn-in
  git pull origin turn-in
ENDSSH
)



