#!/usr/bin/env python
import sys
from src.dns.dnsserver import run
from src.config import config

def arg_parse(args):
    # ensure all arguments are available
    if len(args) == 4 and args[0] == '-p' and args[2] == '-n':
        # cast to int
        name = args[3]
        try:
            port = int(args[1])
        except ValueError as e:
            print "Invalid port number"
            sys.exit(1)
        return (port, name)
    else:
        print 'Correct format is ./dnsserver -p <port> -n <hostname>'
        sys.exit(1)

if __name__ == "__main__":
    conf = config()
    port, name = arg_parse(sys.argv[1:])
    conf.port = port
    conf.name = name
    run(port, name, conf)
