#!/usr/bin/env python
import sys
from src.http.httpserver import run
from src.config import config
def arg_parse(args):
    error = "Correct format is ./httpserver -p <port> -o <origin>"
    if len(args) == 4:
        try:
            port = int(args[1])
        except:
            print error
            sys.exit(1)

        origin = args[3]
        return (port, origin)
    else:
        print error
        sys.exit(1)

if __name__ == "__main__":
    port, origin = arg_parse(sys.argv[1:])
    c = config()
    c.port = port
    c.origin = origin
    run(port, origin, c)
