#!/usr/bin/env python
import sys
def arg_parse(args):
    error = "Correct format is ./httpserver -p <port> -o <origin>"
    if len(args) == 4:
        try:
            port = int(args[1])
        except:
            print error
            sys.exit(1)

        origin = args[3]
        return (port, origin)
    else:
        print error
        sys.exit(1)

if __name__ == "__main__":
    args = arg_parse(sys.argv[1:])
    print args
    print "welcome"
