#!/bin/bash


OPTINDEX=1

# Initialize our own variables:
port=""
origin=""
name=""
user=""
identity=""
numhost=$(wc -l < ./ec2-hosts.txt)

while getopts "p:o:n:u:i:" opt; do
    case "$opt" in
    p)  port=$OPTARG
        ;;
    o)  origin=$OPTARG
        ;;
    n)  name=$OPTARG
        ;;
    u)	user=$OPTARG
	;;
    i)  identity=$OPTARG
	;;
    esac
done
shift $((OPTIND-1))
#echo "port=$port, origin=$origin, name=$name, user=$user, identity=$identity, Not Parsed: $@"

i=0
host=($(cut -d$'\t' -f1 ./ec2-hosts.txt))

for h in "${host[@]}"
do
    ssh -t  -oStrictHostKeyChecking=no -i $identity $user@$h << ENDSSH
    cd /home/$user/CDN
    nohup ./httpserver -p $port -o $origin > http.out 2> http.err < /dev/null &
ENDSSH
wget http://$h:$port/
done

ssh -t  -oStrictHostKeyChecking=no -i $identity $user@cs5700cdnproject.ccs.neu.edu << ENDSSH
    cd /home/$user/CDN
    nohup ./dnsserver -p $port -n $name > dns.out 2> dns.err < /dev/null &
ENDSSH
