#!/bin/bash

OPTINDEX=1

# Initialize our own variables:
port=""
origin=""
name=""
user=""
identity=""
numhost=$(wc -l < ./ec2-hosts.txt)

while getopts "p:o:n:u:i:" opt; do
  case "$opt" in
    p)  port=$OPTARG
      ;;
    o)  origin=$OPTARG
      ;;
    n)  name=$OPTARG
      ;;
    u)  user=$OPTARG
      ;;
    i)  identity=$OPTARG
      ;;
  esac
done
shift $((OPTIND-1))


echo "Running stopCDN against the following arguments:"
echo "port=$port, origin=$origin, name=$name, user=$user, identity=$identity"
echo ""

i=0
host=($(cut -d$'\t' -f1 ./ec2-hosts.txt))

for h in "${host[@]}"; do
  echo ""
  echo "Attempting to stop host ${h}"
  echo ""
  ssh -oStrictHostKeyChecking=no -i $identity $user@$h << ENDSSH &> /dev/null
  pkill python &> /dev/null
  exit
ENDSSH
done

echo ""
echo "Attempting to stop dns server"
echo ""

ssh -oStrictHostKeyChecking=no -i $identity $user@cs5700cdnproject.ccs.neu.edu << ENDSSH &> /dev/null
  pkill python &> /dev/null
  exit
ENDSSH
